services:
  mounter:
    build:
      context: .
    env_file: .env
    # environment:
    #   - SSHFS_REMOTE=user@remote:/path/to/remote
    volumes:
      - ./mnt:/mnt
      - ./examples/tsocks.conf:/etc/tsocks.conf
      - ./examples/known_hosts:/etc/ssh/known_hosts
      - ./examples/id_ed25519:/etc/ssh/key
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
  debug:
    image: busybox:latest
    command: sh -c "sleep 4; ls -la /mnt"
    volumes:
      - ./mnt:/mnt
    depends_on:
      - mounter
    tty: true
