#!/bin/sh
cleanup() {
    echo "unmounting & cleaning up..."
    fusermount -u /mnt
    exit $?
}

trap cleanup INT TERM

sshfs "$SSHFS_REMOTE" /mnt -o _netdev,allow_other,reconnect,idmap=user,ssh_command=/usr/local/bin/ssh-wrapper || exit 1

echo "sleeping..."
sleep infinity &
child_pid=$!

wait $child_pid
cleanup
